# Generated by Django 6.0.1 on 2026-02-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0003_course_catalog_and_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_file',
            field=models.FileField(blank=True, null=True, upload_to='lessons/files/'),
        ),
    ]
